# version: '3.8'

services:
  # --- บริการที่ 1: ฐานข้อมูล PostgreSQL ---
  postgres-db:
    image: postgres:16-alpine
    container_name: nestjs_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    # 🛡️ DevOps Best Practice: ซ่อนพอร์ตฐานข้อมูลจากโลกภายนอก (เอาพอร์ตออก)
    # เพื่อให้เข้าได้เฉพาะจากภายในเน็ตเวิร์กของ Docker เท่านั้น ป้องกันแฮกเกอร์แอบสแกน
    volumes:
      - pgdata:/var/lib/postgresql/data

  # --- บริการที่ 2: แอปพลิเคชัน NestJS ของเรา ---
  api-service:
    build: .
    # ✅ ลบ container_name: nestjs_api ออกแล้ว เพื่อให้ปั๊มเพิ่มหลายตัวได้
    # ✅ ลบ ports: - "3000:3000" ออกแล้ว เพื่อไม่ให้แต่ละร่างแย่งพอร์ตเครื่อง Mac ชนกันเอง
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb
    depends_on:
      - postgres-db

  # --- บริการที่ 3: หน้าด่าน Nginx (Reverse Proxy & Load Balancer) ---
  web-proxy:
    image: nginx:1.25-alpine
    container_name: nestjs_nginx
    ports:
      - "80:80" # เปิดรับพอร์ต 80 ของเครื่องคอมพิวเตอร์เพื่อดักโดเมนจำลอง
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - api-service

  # --- บริการที่ 4: Prometheus (ตัวเก็บสถิติ) ---
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: nestjs_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api-service

  # --- บริการที่ 5: Grafana (หน้าจอแดชบอร์ด) ---
  grafana:
    image: grafana/grafana:10.0.0
    container_name: nestjs_grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
   # --- 🕵️‍♂️ 6. Jaeger (ตัวรับและแสดงผลข้อมูลแกะรอยระบบ) ---
  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: nestjs_jaeger
    ports:
      - "16686:16686" # 🌟 เปิดพอร์ตนี้บนเครื่อง Mac เพื่อเอาไว้เปิดดูหน้าจอค้นหาแผนที่แกะรอย
      - "4317:4317"   # เปิดพอร์ตรับข้อมูลจาก NestJS ผ่านโปรโตคอล OTLP (gRPC)
    restart: always
    
volumes:
  pgdata:
