version: '3.8'

services:
  # --- บริการที่ 1: ฐานข้อมูล PostgreSQL ---
  postgres-db:
    image: postgres:16-alpine
    container_name: nestjs_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # เก็บข้อมูลไว้ในเครื่อง ไม่ให้หายเมื่อสั่งปิดระบบ

  # --- บริการที่ 2: แอปพลิเคชัน NestJS ของเรา ---
  api-service:
    build: .
    container_name: nestjs_api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres-db # ใช้ชื่อ service ของ postgres เป็น host แทน localhost
      DB_PORT: 5432
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb
    depends_on:
      - postgres-db # สั่งให้สร้างฐานข้อมูลให้เสร็จก่อน แล้วค่อยรันตัวแอปตาม
  
  # 🌟 เพิ่มบล็อก Nginx นี้ต่อท้ายเข้าไปในไฟล์เดิม
  web-proxy:
    image: nginx:1.25-alpine
    container_name: nestjs_nginx
    ports:
      - "80:80" # เปิดพอร์ต 80 ของเครื่องคอมพิวเตอร์คุณเพื่อรอรับชื่อโดเมนจำลอง
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - api-service

  # --- 📊 4. Prometheus (ตัวเก็บสถิติ) ---
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: nestjs_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    # ไม่ต้องเปิดพอร์ตออกข้างนอกเพื่อความปลอดภัย ให้คุยกันเองข้างใน Docker network
    ports:
      - "9090:9090" # 🔥 เพิ่มบรรทัดนี้เข้าไปเพื่อให้เข้า http://localhost:9090 จากเครื่อง Mac ได้
  # --- 📈 5. Grafana (หน้าจอแดชบอร์ด) ---
  grafana:
    image: grafana/grafana:10.0.0
    container_name: nestjs_grafana
    ports:
      - "3001:3000" # 🌟 เปิดพอร์ต 3001 บนเครื่องเรา เพื่อเข้าไปดูหน้าจอ Grafana
    depends_on:
      - prometheus
volumes:
  pgdata: # ประกาศตัวเก็บข้อมูลสำหรับ PostgreSQL
