global:
  scrape_interval: 15s # สั่งให้ไปขูดข้อมูลทุกๆ 15 วินาที

scrape_configs:
  - job_name: 'nestjs-app'
    metrics_path: '/metrics' # พาธที่ NestJS พ่นข้อมูลออกมา
    static_configs:
      - targets: ['api-service:3000'] # ชี้ไปที่ชื่อ service ของ NestJS ใน Docker
